### ISSUE TITLE
Plans to build a collapsible items list, like the one used by Google Inbox?

### ISSUE THREAD

**Issue by dandv** [PolymerElements/paper-elements#10]
Like http://materializecss.com/collapsible.html, esp. with the "popout" option.

**Comment by fd** [comment]
:+1:

**Comment by notwaldorf** [comment]
I think you can just build this with an `iron-collapse` element and a styled button (or `paper-item`)

`iron-collapse`: https://elements.polymer-project.org/elements/iron-collapse?view=demo:demo/index.html
`paper-item`: https://elements.polymer-project.org/elements/paper-item?view=demo:demo/index.html
