### ISSUE TITLE
Tags input?

### ISSUE THREAD

**Issue by dandv** [PolymerElements/paper-elements#13]
Any plans to add the tags input used by Google Photos or Google+ ?

![image](https://cloud.githubusercontent.com/assets/33569/7953560/3f52de38-097b-11e5-8903-507cf655b2df.png)

(The functionality in Google Photos could be improved; for example, there's no focus in the tags input, the "remove" icon only appears when you click on a tab etc. StackOverflow does a much better job of handling tag input, but of course it's not Material Design.

**Comment by tjsavage** [comment]
This is a good one - though for the paper elements we stick just to the components explicitly spec'd in the [official material design spec](http://www.google.com/design/spec/). This way there's a single source of truth - we let the team working on material design ordain new visuals as "official material design" before we put them out there as elements. I can't seem to find a spec there specifically for the Google Photos-style tags.

For similar behavior though, I added `chips` to the "Elements Planned" section, which is quite similar and official spec'd: http://www.google.com/design/spec/components/chips.html#
