### ISSUE TITLE
Roadmap for paper-dropdown?

### ISSUE THREAD

**Issue by dominik0711** [PolymerElements/paper-elements#15]
Is there a roadmap when the paper-dropdown will be ready?

**Comment by GabiAxel** [comment]
I implemented paper-dropdown-menu here: https://github.com/GabiAxel/paper-dropdown-menu

Follow #16 to see if it gets accepted.

**Comment by Mygod** [comment]
@GabiAxel Thanks! Using this for now.

**Comment by brianzable** [comment]
Also curious about when the official paper-dropdown will be ready. Any updates?

**Comment by ebidel** [comment]
https://elements.polymer-project.org/elements/paper-dropdown-menu
