### ISSUE TITLE
[contribution] paper-dropdown-menu

### ISSUE THREAD

**Issue by GabiAxel** [PolymerElements/paper-elements#16]
Since I needed paper-dropdown-menu and I didn't know what its status was, I implemented it: https://github.com/GabiAxel/paper-dropdown-menu

Polymer fellows - you are welcome to use it or parts of it, or let me know if I need to make any changes for it to be accepted.

I signed the CLA.

**Comment by nonameolsson** [comment]
Nice! Will this be implemented?

**Comment by manfield** [comment]
Thanks bro.

**Comment by ebidel** [comment]
Closing since https://elements.polymer-project.org/elements/paper-dropdown-menu has been available for awhile.
