### ISSUE TITLE
land paper-dropdown

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/paper-elements#17]
tracking issue for `paper-dropdown` et. al.

**Comment by tigerhawkvok** [comment]
I'm trying to migrate a Polymer app from 0.5 to 1.0, especially  since the `/deep/` and `::shadow` bindings from 0.5 [will be deprecated in Chrome](https://www.chromestatus.com/features/6750456638341120), but I have Polymer `paper-dropdown-menu`s in my 0.5 project -- are you guys working with the Chrome + Chromium team to ensure this lands before `/deep/` is deprecated?

**Comment by tigerhawkvok** [comment]
For anyone else that stumbles across this, I've written the following workaround with `paper-menu-button`: https://gist.github.com/tigerhawkvok/1d570d5605bcd30735ee

As of 2015.07.27, should be functional at [this beta page](http://ssarherps.org/cndb/polymer1beta), and the whole code drop is [here](https://github.com/SSARHERPS/SSAR-species-database/commit/fcbadac8def165377d5a8a1b4c6a8dac414a65f0), if I missed a dependency in the gist.

**Comment by Sinjins** [comment]
Waiting 'patiently' for paper-dropdown-menu 1.0

**Comment by schnie** [comment]
@Sinjins, check out the catalog. It was recently released.. I just used it today! Woo

**Comment by notthetup** [comment]
I don't see a `paper-dropdown-menu` in the catalog. Caching issue? I do see a new `iron-dropdown` though.

**Comment by schnie** [comment]
Ah, yes that and the `paper-menu-button`.  I guess we are still waiting for
the `paper-dropdown-menu`.  Sorry about that!

**Comment by zenorocha** [comment]
+1

**Comment by anantdamle-google** [comment]
I can see it on the catalog but when I download, it doesnt work :-(
![image](https://cloud.githubusercontent.com/assets/8578144/9117338/045dc128-3c87-11e5-9b2c-83f65808deed.png)

**Comment by rubenstolk** [comment]
I think this issue should be closed since `paper-dropdown-menu` is there now... ?

**Comment by addyosmani** [comment]
With `paper-dropdown-menu` now available and in our bower.json, let's close this one. https://github.com/PolymerElements/paper-elements/blob/master/bower.json#L36
