### ISSUE TITLE
Clean bower.json

### ISSUE THREAD

**Issue by lxbrito** [PolymerElements/paper-elements#20]
The 'main' entry is referring to a non-existent file and should be removed.

"main": "paper-elements.html",

**Comment by addyosmani** [comment]
@notwaldorf The Bower spec specifies that `main` is an optional field https://github.com/bower/bower.json-spec/issues/44, even though it will throw a quiet exception if the field is missing. I think we should drop `main` here given that `paper-elements.html` doesn't exist.

**Comment by notwaldorf** [comment]
@addyosmani Yeah, I'll drop it here and everywhere for now. PR a'coming :)
