### ISSUE TITLE
paper-select contribution

### ISSUE THREAD

**Issue by naderio** [PolymerElements/paper-elements#21]
I've implemented `paper-select` element, a mix between a dropdown menu and a tag input à la select2/selectize. ([code](https://github.com/naderio/paper-select),  [docs/demo](http://naderio.github.io/paper-select))

I think this element might have a place within the Polymer paper-elements suite, thus I would like to contribute it.

Thanks

**Comment by tjsavage** [comment]
Thank you for the contribution! Really impressive and complex element. For the paper-elements, we try to stick to only UI elements that have been explicitly defined in the [material design spec](https://www.google.com/design/spec/). [Chips](https://www.google.com/design/spec/components/chips.html#) might be the closest. I think many will find this very useful though!
