### ISSUE TITLE
paper-styles/paper-styles-classes - after font roboto factoring - can no longer be vulcanized

### ISSUE THREAD

**Issue by jlg7** [PolymerElements/paper-elements#25]
Hey there

`font-roboto` was factored out of `paper-styles` into a separate element and yielding import `paper-styles/paper-style-classes.html` to fail upon vulcanization due to resolved path not existing when providing an `abspath`. (30+ other elements compress just fine and resolved path clearly fell a greek dollar short)

https://github.com/PolymerElements/paper-styles/blob/master/classes/typography.html#L10

I am including the elements like so:

```
PolymerElements/paper-elements#=1.0.1
```

which is currently giving me a `PolymerElements/paper-styles#1.0.9`

This failed very obviously via vulcanize + I worked around this pretty easily but thought I'd surface!

Let me know if you need any additional information. 

Cheers!

@jongeho1

**Comment by tjsavage** [comment]
This issue was moved to PolymerElements/font-roboto#7
