### ISSUE TITLE
paper-radio-group single select disrupted

### ISSUE THREAD

**Issue by vikjung** [PolymerElements/paper-elements#29]
paper-radio-group single select gets messed up if anything added around a radio button.  e.g
a div added in one of the radio buttons

paper-radio-group selected="small">
  div>paper-radio-button name="small">Small/paper-radio-button></div>
  paper-radio-button name="medium">Medium/paper-radio-button>
  paper-radio-button name="large">Large/paper-radio-button>
/paper-radio-group>

**Comment by SayChunKim** [comment]
According what i could understand, paper-radio-group allows user to select only one radio button from a set and contains the buttons altogether. If you add div inside the group, its more likely breaking the radio button into multiple sets, allowing multiple clicks possible.

Adding div end tags outside paper-radio-group or not adding anything will not hurt the paper-radio-group. 

Hope helps

**Comment by notwaldorf** [comment]
`paper-radio-group` can only select direct `paper-radio-button` children. It does not support selecting nested children (see https://github.com/PolymerElements/iron-selector/issues/42 for the underlying issue)
