### ISSUE TITLE
Element style location coherency

### ISSUE THREAD

**Issue by M0nter0** [PolymerElements/paper-elements#30]
Some elements have their style in the same file where they are registered, while other elements have it in another file imported.

For example, [paper-toolbar defines it directly](https://github.com/PolymerElements/paper-toolbar/blob/master/paper-toolbar.html#L82) while [paper-header imports it](https://github.com/PolymerElements/paper-header-panel/blob/master/paper-header-panel.html#L117).

Is there any rule/procedure to know when a element import it from another file?

**Comment by ebidel** [comment]
I don't think we have any hard or fast rules. Generally, larger (more shareable) styling is in a separate file, but this has changed a bit with polymer 1.1's styling system. Regardless of how the element does its styling, this should not affect usage of the element.
