### ISSUE TITLE
bower files consistency

### ISSUE THREAD

**Issue by M0nter0** [PolymerElements/paper-elements#31]
Hi!
I'm working with [grunt-bower-task](https://github.com/yatskevich/grunt-bower-task) to vulcanized all the polymer-element files.
Due to [this closed issue at paper-header-panel](https://github.com/PolymerElements/paper-header-panel/issues/24), that element now has set the `main` property at [bower.json](https://github.com/PolymerElements/paper-header-panel/blob/master/bower.json#L13). But I think most of paper elements hasn't. That inconsistency makes more difficult to work with build tools, because we need to check each element to know if it has or not the `main` property set.

I've seen [a question at StackOverflow](http://stackoverflow.com/questions/30511033/grunt-bower-task-and-polymer) referencing the same problem.

**Comment by ebidel** [comment]
AFAIK, bower doesn't really use this property. Can you explain why it's blocking you?

https://github.com/bower/spec/blob/master/json.md#main
