### ISSUE TITLE
In shadow DOM mode, CSS in paper-icon-button demo yields different margins

### ISSUE THREAD

**Issue by viridium** [PolymerElements/paper-elements#37]
In the `paper-icon-button` demo [1], if I switch to shadow DOM [2], the icons have different right margins. This is apparent by inspecting the elements, not by looking at the page.

This might indicate some problems with CSS rule rewriting in the presence of shady DOM.

[1] https://elements.polymer-project.org/elements/paper-icon-button?view=demo:demo/index.html&active=paper-icon-button
[2] https://elements.polymer-project.org/elements/paper-icon-button?view=demo:demo/index.html&active=paper-icon-button&dom=shadow

**Comment by notwaldorf** [comment]
@viridium I'm sorry, I don't think I understand what you mean. I inspected them in the shady/shadow dom, and the icons and the `paper-icon-button` look the same. Which element in particular is different, and which margins are different?

Both the shady and shadow dom produce this:
<img width="407" alt="screen shot 2015-09-01 at 12 43 29 pm" src="https://cloud.githubusercontent.com/assets/1369170/9614523/2870489a-50a7-11e5-93f2-968d0d2bdd76.png">
<img width="526" alt="screen shot 2015-09-01 at 12 43 40 pm" src="https://cloud.githubusercontent.com/assets/1369170/9614527/2da46c4c-50a7-11e5-8a57-710431da7049.png">

**Comment by viridium** [comment]
After troubleshooting, it looks like the margins are the same in both cases, but there is indeed a difference in the way the tools show the margins. In shadow dom mode, the right margin is drawn wider than in shady dom mode. In any case, the fact that the computed margins come up the same way suggests that the issue, if any, is with the tools. Closing.
