### ISSUE TITLE
paper-data-table Tracking Issue

### ISSUE THREAD

**Issue by justinfagnani** [PolymerElements/paper-elements#39]

**Comment by David-Mulder** [comment]
It's not perfect, but it works pretty well: https://github.com/David-Mulder/paper-datatable

**Comment by tjsavage** [comment]
^ this is a pretty excellent element. 

I'll add a section on the roadmap to specifically point out high-quality but non PolymerElements/ elements like this one.

**Comment by aneshas** [comment]
Hey guys, any idea when we will have an official data-table element available?

**Comment by tjsavage** [comment]
No immediate timeline for a Polymer team-built data-table element. We don't see a huge need out there currently, given there are very solid elements already including https://github.com/David-Mulder/paper-datatable and [vaadin-grid](https://github.com/vaadin/vaadin-grid)
