### ISSUE TITLE
Element Request: paper-fab-menu

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/paper-elements#44]
_From @biancashouse on August 18, 2015 0:49_

http://cwdoh.com/paper-fab-menu/components/paper-fab-menu/demo.html

So paper-fab-menu is not a Polymer element ?
It is created on top of Polymer, right ?
Is there a paper Polymer element that does this popup menu functionality ?

_Copied from original issue: PolymerElements/paper-fab#25_

**Comment by ebidel** [comment]
_From @GabiAxel on October 5, 2015 10:54_

I created an element for adding morphing and speed dial to a fab: https://github.com/GabiAxel/paper-fab-transitions/

**Comment by GabiAxel** [comment]
You are welcome to take my implementation or let me know if I should change anything in it.

**Comment by biancashouse** [comment]
Gabriel,

I really appreciate your proactive feedback.
I did start to invest considerable time into using the vaadin elements, but
I soon realised that iOS was making it difficult to use web components, so
I have
completely ripped out web component dependencies. Can't remember the exact
detail, but it seemed to be using html imports breaking GWT.
I will jump back in once Apple have updated Safari to embrace the standard.

Thanks

Ian

**Comment by tjsavage** [comment]
@GabiAxel's element looks quite good for this use-case! Closing here for now.
