### ISSUE TITLE
Register Polymer elements at Bower

### ISSUE THREAD

**Issue by sbley** [PolymerElements/paper-elements#45]
Unlike Polymer itself the elements (e.g. paper-button) are not registered at Bower. Why is that?

**Comment by ebidel** [comment]
I don't remember the historical reasons. Maybe now is the right time now that orgs/repos have settled a big. @tjsavage do determine if this is something we should pursue. 

Other than searchability, what does registering give us?

cc @azakus

**Comment by sbley** [comment]
This is a usecase we have: 
Our Jenkins is behind a firewall and can't access GitHub directly. But it can access the corporate Artifactory server. Using bower-art-resolver and a Remote Bower Repository in Artifactory we could get all bower dependencies from GitHub via Artifactory. But only if the deps can be found in bower's registry at bower.herokuapp.com. So, registering all Polymer elements would help us getting our builds running without direct GitHub access.
Another usecase is WebJars for bower. Those Maven artifacts will get a proper artifactId only if the bower packages are registered.

**Comment by cdata** [comment]
Hi, the Polymer Elements are now registered in the `npm` catalogue. You can install them using commands like the following: `npm install @polymer/paper-button`.

I'm going to close the issue for now. Please re-open if this does not resolve your use case!
