### ISSUE TITLE
paper-behaviors/paper-behaviors.html doesn't exist

### ISSUE THREAD

**Issue by fballiano** [PolymerElements/paper-elements#54]
in this file:
https://github.com/PolymerElements/paper-elements/blob/master/paper-elements.html

there's this line:
<link rel="import" href="../paper-behaviors/paper-behaviors.html">

but the linked file doesn't exists in the paper-behaviors repo.

**Comment by fballiano** [comment]
sorry, part of my comment got deleted cause it was an html tag... i'll write everything again here:

in this file:
https://github.com/PolymerElements/paper-elements/blob/master/paper-elements.html

there's this line:
`<link rel="import" href="../paper-behaviors/paper-behaviors.html">`

but the linked file doesn't exists in the paper-behaviors repo.

**Comment by burn2delete** [comment]
+1

**Comment by cdata** [comment]
Hey, thanks for reporting! This is totally a bug, sorry about that. I noticed that PolymerElements/paper-behaviors#56 is opened to fix it, but honestly I think this fix should occur here in the `paper-elements` repo.
