### ISSUE TITLE
Paper elements look bad with Bootstrap

### ISSUE THREAD

**Issue by eximius313** [PolymerElements/paper-elements#55]
Having just two simple elements in a page:

```
<html>
<head lang="en">
    <meta charset="UTF-8">
    <link rel="stylesheet" href="html/bootstrap/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="html/bootstrap/css/bootstrap-theme.min.css" type="text/css">
    <script src="components/webcomponentsjs/webcomponents-lite.min.js"></script>
    <link rel="import" href="components/paper-radio-button/paper-radio-button.html">
    <link rel="import" href="components/paper-checkbox/paper-checkbox.html">
</head>
<body>
    <div class="row">
        <div class="col-lg-4">
            <paper-checkbox>My checkbox</paper-checkbox>
            <br/>
            <paper-radio-button>My Radio</paper-radio-button>
        </div>
    </div>
</body>
</html>

```

results in this
Firefox:
![image](https://cloud.githubusercontent.com/assets/5578017/11171305/ebd04508-8bec-11e5-85cd-30e953e547e4.png)

Chrome:
![image](https://cloud.githubusercontent.com/assets/5578017/11171308/13a906e6-8bed-11e5-8ec0-e350dc2e3c7a.png)

One can clearly see that in Firefox both checkbox and radio button are badly rendered, and in Chrome checkbox is not displayed properly.

**Comment by notwaldorf** [comment]
This is a general problem with the Shady DOM, which doesn't offer true CSS encapsulation

**Comment by notwaldorf** [comment]
Here's a JSBin most of the `paper-elements`, with the bootstrap CSS applied: https://jsbin.com/kipufoh/edit?html,output

The only one looking bad is `paper-checkbox`, and that's being tracked and fixed here: https://github.com/PolymerElements/paper-checkbox/issues/104

Closing, since most of this is fixed.
