### ISSUE TITLE
Element request: paper-subheader

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/paper-elements#63]
Material spec: https://www.google.com/design/spec/components/subheaders.html

**Comment by notwaldorf** [comment]
Isn't a `subheader` just a div with `position:fixed`? I'm not sure this needs to be its own element, but I'll let @tjsavage decide

**Comment by tjsavage** [comment]
It seems like there's the basic sub-header - which could just be a position: fixed div - and also the sticky header as part of a lock scrolling list. The second one seems like it might actually be a potential advanced feature for something like `iron-list`?

**Comment by abdonrd** [comment]
Closing very old issue...
