### ISSUE TITLE
Add paper-divider third-party element as alternative

### ISSUE THREAD

**Issue by patrinhani-ciandt** [PolymerElements/paper-elements#64]
Check if it's possible to add this paper-chip component as a third-party element:
https://github.com/WebPaperElements/paper-divider based on (https://www.google.com/design/spec/components/dividers.html)
Here is the Demo: http://webpaperelements.github.io/paper-divider/components/paper-divider/demo/

**Comment by notwaldorf** [comment]
I don't think it's very likely we would bring this in, since it seems to be basically a styled `<hr>` tag, but @tjsavage can correct me if i'm wrong.
