### ISSUE TITLE
molecules repo gone

### ISSUE THREAD

**Issue by 7Ds7** [PolymerElements/paper-elements#66]
Sorry about the off topic regarding paper-elements but i really do not know where to put this.

Where did the PolymerElements/molecules git repo went ?
I noticed it was named differently from all the others since always ex: PolymerElements/paper-elements but now it is just gone, any plans for it to come back? Was it moved somewhere else ?

Thanks and once again sorry for the off topic

**Comment by notwaldorf** [comment]
Good news, it's back: https://github.com/polymerelements/molecules 🎉
