### ISSUE TITLE
paper-submenu

### ISSUE THREAD

**Issue by wuxiaoying** [PolymerElements/paper-elements#7]
paper-menu is still missing paper-submenu, and it's not on the road map at the moment.

**Comment by mrkswrnr** [comment]
+1

**Comment by mrkswrnr** [comment]
+1

**Comment by EckhardSchoenknecht** [comment]
need this submenu too, thx

**Comment by tjsavage** [comment]
Added to "Planning to Build" - on the roadmap! Look for it in a few weeks.

**Comment by demaass** [comment]
+1
would be nice to have :)

**Comment by SayChunKim** [comment]
+1

Hope it's ready soon enough. Can't wait to test it

**Comment by wkeizer** [comment]
Any news yet on this planned element?

**Comment by cardimajs** [comment]
+1

**Comment by Foorack** [comment]
+1

**Comment by notwaldorf** [comment]
`paper-submenu` has been released on Friday. It lives in the `paper-menu` repo: https://github.com/PolymerElements/paper-menu

**Comment by MarkDurbin104** [comment]
I'm finding it hard to implement closeDrawer on a combination of paper-menu and paper-submenu **only** triggering via on-iron-activate="_listTap" on leaf nodes. Is there a preferred way to do this?
i.e. where to put  `on-iron-activate` event handler on:

```
<paper-menu>
   <paper-item class="list">Home</paper-item>
   <paper-submenu>
       <paper-item class="menu-trigger">Topics</paper-item>
       <paper-menu class="menu-content sublist">
           <paper-item>Topic 1</paper-item>
           <paper-item>Topic 2</paper-item>
           <paper-item>Topic 3</paper-item>
       </paper-menu>
   </paper-submenu>
</paper-menu>
```
