### ISSUE TITLE
Recent commits might have contained some breaking changes

### ISSUE THREAD

**Issue by govis** [PolymerElements/paper-elements#71]
![image](https://cloud.githubusercontent.com/assets/971651/13148460/7be498c8-d62b-11e5-92a7-89396823d8fb.png)
![image](https://cloud.githubusercontent.com/assets/971651/13148469/845b27b0-d62b-11e5-83da-e9e512196441.png)

**Comment by abdonrd** [comment]
In the `paper-tabs`, there seems no default colors.

Reference issue: https://github.com/PolymerElements/paper-tabs/issues/114
My PR to fix it (declined): https://github.com/PolymerElements/paper-tabs/pull/55

**Comment by govis** [comment]
looks like it's back to normal with the 1.3.0 release
