### ISSUE TITLE
clean deprecated stuff out of your elements please

### ISSUE THREAD

**Issue by gertcuykens** [PolymerElements/paper-elements#72]
https://ebidel.github.io/material-playground/

![image](https://cloud.githubusercontent.com/assets/863731/14939245/e7990350-0f3e-11e6-9d5b-3808ea27b78a.png)

Is it ebidel his stuff that is old or are there still elements that need to be updated?

**Comment by notwaldorf** [comment]
It's @ebidel. None of our elements generate deprecation warnings
