### ISSUE TITLE
Missing Docs/Demo?

### ISSUE THREAD

**Issue by notwaldorf** [PolymerElements/paper-elements#73]
_From @MoonDawg92 on June 8, 2016 0:7_

Can we expect to see documentation and/or a demo for paper-swatch-picker anytime soon?

The page is currently blank: https://elements.polymer-project.org/elements/paper-swatch-picker

The bower install command is also undefined on the left hand side of the page.

_Copied from original issue: PolymerElements/paper-swatch-picker#8_

**Comment by notwaldorf** [comment]
I think this is because the element is missing from the list of `paper-elements`: it's not actually navigatable from https://elements.polymer-project.org/browse?package=paper-elements.

**Comment by notwaldorf** [comment]
@MoonDawg92 If you'd be interested in sending a PR for this, it would be greatly appreciated! 🍰

**Comment by stramel** [comment]
@notwaldorf Are you looking for someone to create a PR that will start the addition process to paper-elements?

**Comment by WaverleyDesign** [comment]
Where is the list of registered elements for the Paper elements package in the catalog?

**Comment by notwaldorf** [comment]
All the paper elements are here: https://elements.polymer-project.org/browse?package=paper-elements

**Comment by WaverleyDesign** [comment]
@notwaldorf But from where is that list sourced? I thought I could just add the swatch-picker to that registry?

**Comment by notwaldorf** [comment]
@WaverleyDesign Oh, from the `bower.json` in this repo:https://github.com/PolymerElements/paper-elements/blob/master/bower.json
Sorry I misunderstood your question!

**Comment by notwaldorf** [comment]
Should have been fixed in https://github.com/PolymerElements/paper-elements/pull/74 -- it will take a bit to make it in the catalog, since it will need a re-release

**Comment by stramel** [comment]
@notwaldorf Thank you for putting together this awesome component! :+1:

**Comment by TheMoonDawg** [comment]
@notwaldorf Somehow missed seeing your request for a PR. Sorry about that! Luckily, @stramel took the initiative!
